/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author PC
 */
public class ClienteVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteVista.class.getName());

    /**
     * Creates new form ClienteVista
     */
    public ClienteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlTitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDpi = new javax.swing.JLabel();
        lblFNacimiento = new javax.swing.JLabel();
        lblFRegistro = new javax.swing.JLabel();
        lblTelefono4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtId2 = new javax.swing.JTextField();
        txtId3 = new javax.swing.JTextField();
        txtId4 = new javax.swing.JTextField();
        txtId5 = new javax.swing.JTextField();
        txtId6 = new javax.swing.JTextField();
        txtId7 = new javax.swing.JTextField();
        txtId8 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(0, 0, 51));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jlTitulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("CLIENTE FUTBOLERO MUNDIAL 2026");
        panelHeader.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 620, 120));

        jlTitulo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jlTitulo1.setText("CLIENTE FUTBOLERO MUNDIAL 2026");
        panelHeader.add(jlTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 620, 150));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 160, 70));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 160, 60));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 20, 70));

        jPanel5.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 70));

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, 70));

        jPanel7.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 70));

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Nombre");
        panelHeader.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        lblApellido.setBackground(new java.awt.Color(255, 255, 255));
        lblApellido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido");
        panelHeader.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 30));

        lblDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Direccion");
        panelHeader.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        panelHeader.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 30));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Id");
        panelHeader.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        lblDpi.setBackground(new java.awt.Color(255, 255, 255));
        lblDpi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDpi.setForeground(new java.awt.Color(255, 255, 255));
        lblDpi.setText("Dpi");
        panelHeader.add(lblDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        lblFNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFNacimiento.setText("Fecha Nacimiento");
        panelHeader.add(lblFNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 30));

        lblFRegistro.setBackground(new java.awt.Color(255, 255, 255));
        lblFRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFRegistro.setText("Fecha Registro");
        panelHeader.add(lblFRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 30));

        lblTelefono4.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefono4.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono4.setText("Telefono");
        panelHeader.add(lblTelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));
        panelHeader.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 250, 30));
        panelHeader.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 250, 30));
        panelHeader.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 250, 30));
        panelHeader.add(txtId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 250, 30));
        panelHeader.add(txtId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 250, 30));
        panelHeader.add(txtId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 250, 30));
        panelHeader.add(txtId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 250, 30));
        panelHeader.add(txtId8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 250, 30));

        btnActualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        panelHeader.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 100, 50));

        btnConsultar.setBackground(new java.awt.Color(255, 51, 0));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        panelHeader.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 100, 50));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        panelHeader.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 100, 50));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("INSERTAR");
        panelHeader.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDpi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFNacimiento;
    private javax.swing.JLabel lblFRegistro;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono4;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtId3;
    private javax.swing.JTextField txtId4;
    private javax.swing.JTextField txtId5;
    private javax.swing.JTextField txtId6;
    private javax.swing.JTextField txtId7;
    private javax.swing.JTextField txtId8;
    // End of variables declaration//GEN-END:variables
}
