/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controller.ClienteController;
import Modelo.Cliente;
import java.time.LocalDateTime;
import java.util.Date;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class ClienteVista extends javax.swing.JFrame {
    private final ClienteController controlador = new ClienteController();
    private final DefaultTableModel modeloTabla = new DefaultTableModel(new Object []{"id " , " nombre " , " apellido " , " telefono " , " email " , " direccion " ," dpi "," fecha_nacimiento ", " fecha_registro "},0);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteVista.class.getName());

    /**
     * Creates new form ClienteVista
     */
    public ClienteVista() {
        initComponents();
        jtCliente.setModel(modeloTabla);
        jtCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        
jtCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
jtCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
jtCliente.getColumnModel().getColumn(2).setPreferredWidth(150);
jtCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
jtCliente.getColumnModel().getColumn(4).setPreferredWidth(200);
jtCliente.getColumnModel().getColumn(5).setPreferredWidth(250);
jtCliente.getColumnModel().getColumn(6).setPreferredWidth(120);
jtCliente.getColumnModel().getColumn(7).setPreferredWidth(120);
jtCliente.getColumnModel().getColumn(8).setPreferredWidth(180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlTitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDpi = new javax.swing.JLabel();
        lblFNacimiento = new javax.swing.JLabel();
        lblFRegistro = new javax.swing.JLabel();
        lblTelefono4 = new javax.swing.JLabel();
        txtDpi = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtFN = new com.toedter.calendar.JDateChooser();
        jdFR = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(0, 0, 51));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jlTitulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 34)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("CLIENTE FUTBOLERO MUNDIAL 2026");
        panelHeader.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 620, 120));

        jlTitulo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 34)); // NOI18N
        jlTitulo1.setText("CLIENTE FUTBOLERO MUNDIAL 2026");
        panelHeader.add(jlTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 620, 150));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 160, 70));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 60));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 160, 60));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 20, 70));

        jPanel5.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 70));

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 20, 70));

        jPanel7.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelHeader.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 70));

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Nombre");
        panelHeader.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, 30));

        lblApellido.setBackground(new java.awt.Color(255, 255, 255));
        lblApellido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido");
        panelHeader.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 30));

        lblDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Direccion");
        panelHeader.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 30));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        panelHeader.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 30));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Id");
        panelHeader.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        lblDpi.setBackground(new java.awt.Color(255, 255, 255));
        lblDpi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDpi.setForeground(new java.awt.Color(255, 255, 255));
        lblDpi.setText("Dpi");
        panelHeader.add(lblDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 30));

        lblFNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        lblFNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFNacimiento.setText("Fecha Nacimiento");
        panelHeader.add(lblFNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 30));

        lblFRegistro.setBackground(new java.awt.Color(255, 255, 255));
        lblFRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFRegistro.setText("Fecha Registro");
        panelHeader.add(lblFRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 30));

        lblTelefono4.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTelefono4.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono4.setText("Telefono");
        panelHeader.add(lblTelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));
        panelHeader.add(txtDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 250, 30));
        panelHeader.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 250, 30));
        panelHeader.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 250, 30));
        panelHeader.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 250, 30));
        panelHeader.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 250, 30));
        panelHeader.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 250, 30));
        panelHeader.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 250, 30));

        btnActualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        panelHeader.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 110, 50));

        btnConsultar.setBackground(new java.awt.Color(255, 51, 0));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);
        panelHeader.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 110, 50));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panelHeader.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 110, 50));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("INSERTAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        panelHeader.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, 50));
        panelHeader.add(txtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 413, 250, 30));
        panelHeader.add(jdFR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 453, 250, 30));

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCliente);

        panelHeader.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 650, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarCliente(){
        modeloTabla.setRowCount(0);
        for(Cliente cl : controlador.listarCliente()){
            modeloTabla.addRow(new Object[]{ cl.getId(),
                cl.getNombre(),
                cl.getApellido(),
                cl.getTelefono(),
                cl.getEmail(),
                cl.getDireccion(),
                cl.getDpi(),
                cl.getFecha_nacimiento(),
                cl.getFecha_registro()
                
            });
        }
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controlador.insertarCliente(txtNombre.getText(),
                txtApellido.getText(), 
                txtTelefono.getText(),
                txtEmail.getText(),
                txtDireccion.getText(), 
                txtDpi.getText(),
                txtFN.getDate()
        );
        cargarCliente();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
                                          
    int fila = jtCliente.getSelectedRow();
    
    if (fila != -1) {
        // Obtener el ID de la columna 0
        int idCliente = Integer.parseInt(jtCliente.getValueAt(fila, 0).toString());

        controlador.actualizarCliente(
            idCliente,               
            txtNombre.getText(),
            txtApellido.getText(),
            txtTelefono.getText(),
            txtEmail.getText(),
            txtDireccion.getText(),
            txtDpi.getText(),
            txtFN.getDate()
        );

        cargarCliente();
        JOptionPane.showMessageDialog(this, "Cliente actualizado");
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla");
    }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        cargarCliente();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int fila = jtCliente.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla");
    } else {
        // Obtenemos el ID de la columna 0
        String idString = jtCliente.getValueAt(fila, 0).toString();
        int idReal = Integer.parseInt(idString);
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar al cliente con ID: " + idReal + "?");
        
        if (confirmar == JOptionPane.YES_OPTION) {

            controlador.eliminarCliente(idReal); 
            
            cargarCliente(); 
            limpiarCampos(); // Limpiar los cuadros de texto
            JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito");
        }

}
    

    }//GEN-LAST:event_btnEliminarActionPerformed
private void limpiarCampos() {    
    txtNombre.setText("");
    txtApellido.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");
    txtDireccion.setText("");
    txtDpi.setText("");
    
    if (txtFN != null) {
        txtFN.setDate(null);
    }
}
    private void jtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClienteMouseClicked
        // TODO add your handling code here:                                       
    int fila = jtCliente.getSelectedRow();
    if (fila != -1) {
        
        // Obtenemos los datos de la fila seleccionada
        String nombre = jtCliente.getValueAt(fila, 1).toString();
        String apellido = jtCliente.getValueAt(fila, 2).toString();
        String telefono = jtCliente.getValueAt(fila, 3).toString();
        String email = jtCliente.getValueAt(fila, 4).toString();
        String direccion = jtCliente.getValueAt(fila, 5).toString();
        String dpi = jtCliente.getValueAt(fila, 6).toString();
        
        // Llenamos los campos de texto
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtTelefono.setText(telefono);
        txtEmail.setText(email);
        txtDireccion.setText(direccion);
        txtDpi.setText(dpi);
        
        try {
            java.util.Date fecha = (java.util.Date) jtCliente.getValueAt(fila, 7);
            txtFN.setDate(fecha);
        } catch (Exception e) {
            System.err.println("Error al cargar fecha: " + e.getMessage());
        }
    }
    
    }//GEN-LAST:event_jtClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteVista().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdFR;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTitulo1;
    private javax.swing.JTable jtCliente;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDpi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFNacimiento;
    private javax.swing.JLabel lblFRegistro;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono4;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtEmail;
    private com.toedter.calendar.JDateChooser txtFN;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   
}
